services:
  # Base de datos PostgreSQL
  - type: pserv
    name: tarde-crecimiento-drive-db
    env: docker
    plan: free
    region: oregon
    ipAllowList: []

  # Servicio web de NestJS
  - type: web
    name: tarde-crecimiento-drive
    env: node
    region: oregon
    plan: free
    buildCommand: npm ci --omit=dev && npm install --save-dev @nestjs/cli typescript && NODE_OPTIONS="--max-old-space-size=460" npx prisma generate && NODE_OPTIONS="--max-old-space-size=460" npm run build
    startCommand: npm run db:migrate && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: tarde-crecimiento-drive-db
          property: connectionString
      - key: PORT
        value: 10000
      # Agrega tus variables de entorno de Google OAuth aqu√≠
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
    healthCheckPath: /
